apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dev-frontend-cert
  namespace: thetym
spec:
  secretName: tls-secret
  dnsNames:
    - devnew.thetym.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
