apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: devnew-thetym-cert
  namespace: thetym
spec:
  secretName: devnew-thetym-tls-secret
  issuerRef:
    name: letsencrypt-staging  # Change to your issuer's name (e.g., letsencrypt-prod) for production
    kind: ClusterIssuer
  dnsNames:
    - devnew.thetym.com
