apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/instance: dev-frontend
  name: dev-frontend-tls
  namespace: thetym
spec:
  dnsNames:
    - devaccount.thetym.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: dev-frontend-tls

