apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
    app.kubernetes.io/instance: backend
  name: backend
  namespace: thetym
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - env:
            - name: SPRING_DATA_MONGODB_URI
              value: >-
               mongodb+srv://admin:bbs2020@cluster0.ohkfp.mongodb.net/testdb?retryWrites=true&w=majority
          image: docker.io/ramesh10654/thetymbackend:v1.3
          imagePullPolicy: IfNotPresent
          name: backend
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "2"   # 2 CPU
              memory: "4Gi"  # 4 Gibibyte
            requests:
              cpu: "0.5"   # 2 CPU
              memory: "1Gi"  # 2 Gibibyte
      imagePullSecrets:
        - name: dockerhub-secret
