apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-frontend
  namespace: thetym
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-frontend
  template:
    metadata:
      labels:
        app: dev-frontend
    spec:
      containers:
      - name: dev-frontend
        image: docker.io/ramesh10654/dev-frontend:1.0.2
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 10

