apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-frontend-ingress
  namespace: thetym
spec:
  rules:
  - host: devnew.thetym.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dev-frontend
            port:
              number: 80
