apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-frontend-ingress
  namespace: thetym
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - devaccount.thetym.com
    secretName: dev-frontend-tls
  rules:
  - host: devaccount.thetym.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dev-frontend
            port:
              number: 80
