apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-frontend-ingress
  namespace: thetym
  annotations:
    kubernetes.io/ingress.class: "nginx"  # Example annotation for specifying the Ingress class
spec:
  ingressClassName: nginx  # Ingress class specified here
  rules:
  - host: devnew.thetym.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dev-frontend
            port:
              number: 80
