apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    app.kubernetes.io/instance: dev-backend
  name: dev-backend-ingress
  namespace: argo-rollouts
spec:
  ingressClassName: nginx  # This line might be unnecessary as you're already specifying the class in annotations.
  rules:
    - host: devaccount.thetym.com
      http:
        paths:
          - backend:
              service:
                name: dev-backend
                port:
                  number: 80
            path: /
            pathType: Prefix
