apiVersion: v1
kind: Secret
metadata:
  name: mongodb-uri-secret
  namespace: argo-rollouts
type: Opaque
data:
  mongodb-uri: bW9uZ29kYitzcnY6Ly9hZG1pbjpiYnMyMDIwQGNsdXN0ZXIwLm9oa2ZwLm1vbmdvZGIubmV0L2JldGFuZXcxP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eQ==
