apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: dev-backend
  namespace: argo-rollouts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-backend
  template:
    metadata:
      labels:
        app: dev-backend
    spec:
      containers:
      - name: dev-backend
        image: docker.io/dinesh10275/dev-backend:v1.0
        ports:
        - containerPort: 80
        env:
            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb+srv://admin:bbs2020@cluster0.ohkfp.mongodb.net/betanew1?retryWrites=true&w=majority"
            - name: baseUrl
              value: "https://devaccount.thetym.com/thetym-service/"
            - name: frontEndUrl
              value: "https://dev.thetym.com/"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      imagePullSecrets:
      - name: dockerhub-secret-backend
  strategy:
    canary:
      steps:
      - setWeight: 10
      - pause: 
          duration: 1m
