apiVersion: v1
kind: Service
metadata:
  name: dev-frontend
  namespace: thetym
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30002
  selector:
    app: dev-frontend
