apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: thetym
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 31000
  selector:
    app: backend
