apiVersion: v1
kind: Service
metadata:
  name: dev-frontend
  namespace: thetym
spec:
  type: ClusterIP  # Change the type to ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: dev-frontend

